DSWA/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home_view, name='home'),

    path('accounts/logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('accounts/profile/edit', views.profile_edit, name='profile_edit'),
    path('accounts/delete/', views.delete_account_view, name='delete'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('data/edit/<int:data_id>/', views.edit_data, name='edit_data'),
    path('data/delete/<int:data_id>/', views.delete_data, name='delete_data'),
    path('data/view/<int:data_id>/', views.view_data, name='view_data'),
    path('data/add-data/', views.add_data, name='add_data'),

    path('data_updated/', views.data_updated, name='data_updated'),
    path('access_denied/', views.access_denied, name='access_denied'),


]

DevelopmentSecureWebApplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('DSWA.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('DSWA.urls')),
]

DSWA/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    date_of_birth = models.DateField(verbose_name='Дата рождения', null=True, blank=True)
    gender = models.CharField(verbose_name='Гендер',
                              max_length=10,
                              choices=[('Ж', "Женский"), ('М', "Мужской")],
                              default='М')
    is_verified = models.BooleanField(verbose_name='is_verified', default=False)

    encryption_key = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username


class ConfidentialData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_encrypted = models.BooleanField(default=False)

    encryption_key = models.CharField(max_length=255, null=True, blank=True)


    class Meta:
        verbose_name = 'Confidential Data'
        verbose_name_plural = 'Confidential Data'

    def __str__(self):
        return f'Confidential Data #{self.id}'


class AuditLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=100)
    ip_address = models.GenericIPAddressField()
    success = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Audit Log'
        verbose_name_plural = 'Audit Logs'

    def __str__(self):
        return f'Audit Log #{self.id}'

templates/access_denied.html
<!DOCTYPE html>
<html>
<head>
    <title>Access Denied</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        h1 {
            font-size: 32px;
            text-align: center;
            margin-top: 50px;
        }

        p {
            font-size: 18px;
            text-align: center;
            margin-top: 20px;
        }

        .button-container {
            text-align: center;
            margin-top: 30px;
        }

        .button-container {
            text-align: center;
            margin-top: 30px;
        }

        .button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .button:hover {
            background-color: #444;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>Доступ запрещен</h1>
    <p>К сожалению, вам не разрешено редактировать эти данные из-за ограничений политики конфиденциальности.</p>

{% endblock %}

</body>
</html>

templates/add_data.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title>Add Data</title>#}
{#    <style>#}
{#        body {#}
{#            background-color: #000;#}
{#            color: #fff;#}
{#            font-family: "Arial", sans-serif;#}
{#        }#}
{##}
{#        h2 {#}
{#            font-size: 24px;#}
{#            text-align: center;#}
{#            margin-top: 50px;#}
{#        }#}
{##}
{#        form {#}
{#            margin-top: 30px;#}
{#            text-align: center;#}
{#        }#}
{##}
{#        form p {#}
{#            margin-bottom: 10px;#}
{#        }#}
{##}
{#        input[type="text"], input[type="password"] {#}
{#            padding: 5px;#}
{#            width: 200px;#}
{#        }#}
{##}
{#        button {#}
{#            padding: 10px 20px;#}
{#            background-color: #222;#}
{#            color: #fff;#}
{#            border: none;#}
{#            cursor: pointer;#}
{#        }#}
{##}
{#        button:hover {#}
{#            background-color: #444;#}
{#        }#}
{#    </style>#}
{#</head>#}
{#<body>#}
{#{% extends 'home.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{##}
{#    <h2>Добавление защищенной записи</h2>#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Добавить</button>#}
{#    </form>#}
{##}
{#{% endblock %}#}
{##}
{#</body>#}
{#</html>#}

<!DOCTYPE html>
<html>
<head>
    <title>Add Data</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        .container {
            max-width: 450px;
            margin: 0 auto;
            padding: 70px;
            margin-top: 60px;
            background-color: #222;
            border-radius: 10px;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            text-align: center;
        }

        form p {
            margin-bottom: 10px;
        }

        input[type="text"], textarea {
            padding: 10px;
            width: 100%;
            margin-bottom: 20px;
            border-radius: 5px;
            border: none;
            resize: vertical;
        }

        button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }

        button:hover {
            background-color: #444;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <h2>Добавление Confidential Data</h2>
        <form method="post">
            {% csrf_token %}
            <p>
                <input type="text" name="title" placeholder="Заголовок" required>
            </p>
            <p>
                <textarea name="description" rows="5" placeholder="Описание" required></textarea>
            </p>
            <button type="submit">Добавить</button>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        h1 {
            font-size: 32px;
            text-align: center;
            margin-top: 50px;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-top: 30px;
        }

        table {
            margin: 0 auto;
            border-collapse: collapse;
            width: 80%;
            margin-top: 50px;
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #222;
            color: #fff;
            font-size: 18px;
        }

        td {
            background-color: #444;
            color: #fff;
            font-size: 16px;
        }

        tr:nth-child(even) {
            background-color: #333;
        }

        .edit-button {
            padding: 5px 10px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .edit-button:hover {
            background-color: #444;
        }

    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}
    <br>
    <br>
    <h1>Добро пожаловать на Dashboard</h1>

    <h2>Confidential Data</h2>

    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>CD</th>
            <th>Title</th>
            <th>Description</th>
            <th>Is Encrypted</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for data in confidential_data %}
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data }}</td>
                {% if data.encryption_key != user.encryption_key %}
                    <td>-</td>
                    <td>***</td>
                {% else %}
                    <td>{{ data.title }}</td>
                    {#                    <td>{{ data.description }}</td>#}
                    <td>****</td>
                {% endif %}
                <td>{{ data.is_encrypted }}</td>
                <td>
                    <form method="GET" action="{% url 'view_data' data_id=data.id %}" style="display: inline;">
                        {% csrf_token %}
                        <button class="edit-button">Просмотр</button>
                    </form>
                    <form method="GET" action="{% url 'edit_data' data_id=data.id %}" style="display: inline;">
                        {% csrf_token %}
                        <button class="edit-button">Изменить</button>
                    </form>
                    <form method="GET" action="{% url 'delete_data' data_id=data.id %}" style="display: inline;">
                        {% csrf_token %}
                        <button class="edit-button">Удалить</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



    <script>
        function editData(id) {
            console.log("Editing data with ID:", id);
        }
    </script>
{% endblock %}
</body>
</html>

templates/data_updated.html
<!DOCTYPE html>
<html>
<head>
    <title>Data Updated</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        h1 {
            font-size: 32px;
            text-align: center;
            margin-top: 50px;
        }

        p {
            font-size: 18px;
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>Данные успешно обновлены</h1>
    <p>Ваши данные были успешно обновлены.</p>

{% endblock %}

</body>
</html>

templates/delete_data.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirmation - Delete Record</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        .container {
            max-width: 450px;
            margin: 0 auto;
            padding: 70px;
            margin-top: 60px;
            background-color: #222;
            border-radius: 10px;
        }

        .container2 {
            max-width: 300px;
            margin: 0 auto;
            padding: 70px;
            margin-top: 30px;
            background-color: #111;
            border-radius: 10px;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-top: 50px;
        }

        p {
            font-size: 18px;
            text-align: center;
            margin-top: 20px;
        }

        form {
            text-align: center;
            margin-top: 30px;
        }

        button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #444;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}
    <br>
    <div class="container">
        <h2>Подтверждение - Удалить запись</h2>
        <p>Вы уверены, что хотите удалить эту запись?</p>
        <div class="container2">
            <p>Date: {{ data }}</p>
            <p>Title: {{ data.title }}</p>
            <p>Description: {{ data.description }}</p>
        </div>
        <form method="post" action="{% url 'delete_data' data.id %}">
            {% csrf_token %}
            <button type="submit">Удалить</button>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

</body>
</html>

templates/edit_data.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title>Edit Confidential Data</title>#}
{#    <style>#}
{#        body {#}
{#            background-color: #000;#}
{#            color: #fff;#}
{#            font-family: "Arial", sans-serif;#}
{#        }#}
{##}
{#        h1 {#}
{#            font-size: 32px;#}
{#            text-align: center;#}
{#            margin-top: 50px;#}
{#        }#}
{##}
{#        form {#}
{#            margin-top: 50px;#}
{#            text-align: center;#}
{#        }#}
{##}
{#        form p {#}
{#            margin-bottom: 10px;#}
{#        }#}
{##}
{#        input[type="text"], input[type="password"] {#}
{#            padding: 5px;#}
{#            width: 200px;#}
{#        }#}
{##}
{#        button {#}
{#            padding: 10px 20px;#}
{#            background-color: #222;#}
{#            color: #fff;#}
{#            border: none;#}
{#            cursor: pointer;#}
{#        }#}
{##}
{#        button:hover {#}
{#            background-color: #444;#}
{#        }#}
{#    </style>#}
{#</head>#}
{#<body>#}
{#{% extends 'home.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{#    <br>#}
{#    <br>#}
{##}
{#    <h1>Редактирование Confidential Data</h1>#}
{##}
{#    <form method="POST">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{##}
{#        <button type="submit">Сохранить</button>#}
{#    </form>#}
{#{% endblock %}#}
{##}
{#</body>#}
{#</html>#}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Confidential Data</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        .container {
            max-width: 450px;
            margin: 0 auto;
            padding: 70px;
            margin-top: 60px;
            background-color: #222;
            border-radius: 10px;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-bottom: 30px;
        }

        h1 {
            font-size: 32px;
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            text-align: center;
        }

        form p {
            margin-bottom: 10px;
        }

        input[type="text"], input[type="password"] {
            padding: 10px;
            width: 100%;
            margin-bottom: 20px;
            border-radius: 5px;
            border: none;
        }

        button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }

        button:hover {
            background-color: #444;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}

    <div class="container">
        {#    <h1>Редактирование Confidential Data</h1>#}
        <h2>Редактирование Confidential Data</h2>
        <form method="POST">
            {% csrf_token %}
            <p>
                <input type="text" name="title" value="{{ form.title.value }}" required>
            </p>
            <p>
                <input type="text" name="description" value="{{ form.description.value }}" required>
            </p>
 <p>
            <label>
                <input type="checkbox" name="is_encrypted" {% if form.is_encrypted.value %}checked{% endif %}>
                Is Encrypted
            </label>
        </p>
            <button type="submit">Сохранить</button>
        </form>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}
</body>
</html>

templates/home.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title>Home</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Welcome to the Home Page</h1>#}
{##}
{#    <p>This is the home page of the secure data management web application.</p>#}
{##}
{#    <h2>Features</h2>#}
{#    <ul>#}
{#        <li>Secure storage of confidential data</li>#}
{#        <li>User authentication and authorization</li>#}
{#        <li>Data encryption and secure transmission</li>#}
{#        <li>Protection against common web application attacks</li>#}
{#        <li>Audit and logging system</li>#}
{#        <li>Automatic updates and security patches</li>#}
{#        <li>Security testing and vulnerability fixes</li>#}
{#    </ul>#}
{##}
{#    <p>Start using the application by <a href="/login/">logging in</a>.</p>#}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #222;
            padding: 20px;
            text-align: center;
        }

        h1 {
            font-size: 32px;
            margin: 0;
        }

        nav {
            margin-top: 20px;
            text-align: center;
        }

        nav a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-top: 50px;
        }

        p {
            font-size: 18px;
            text-align: center;
            margin-top: 20px;
        }

        .button-container {
            text-align: center;
            margin-top: 30px;
        }

        .button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .button:hover {
            background-color: #444;
        }

        footer {
            background-color: #222;
            padding: 20px;
            text-align: center;
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
        }

        footer p {
            margin: 0;
            color: #999;
            font-size: 14px;
        }
    </style>
</head>
<body>
<header>
    <h1>Secure Website</h1>
    <nav>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'dashboard' %}">Dashboard</a>
        <a href="{% url 'add_data' %}">Добавить запись</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Личный кабинет</a>
            <a href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'login' %}">Войти</a>
            <a href="{% url 'register' %}">Регистрация</a>
        {% endif %}
    </nav>
</header>
{% block content %}

    <h2>Добро пожаловать {{ user.username }} на Home Page</h2>
    <p>Это домашняя страница нашего веб-сайта.</p>
    <br>
    <br>

    <div class="button-container">
        <a href='{% url 'dashboard' %}' class="button">Перейти в Dashboard</a>
    </div>


{% endblock %}
<footer>
    <p>Developed by Ilya Kharchenko &copy; 2023. Все права защищены.</p>
</footer>
</body>
</html>

templates/lk.html
<!DOCTYPE html>
<html>
<head>
    <title>Личный кабинет</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #222;
            padding: 20px;
            text-align: center;
        }

        h1 {
            font-size: 32px;
            margin: 0;
        }

        nav {
            margin-top: 20px;
            text-align: center;
        }

        nav a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }

        .profile-container {
            margin-top: 50px;
            text-align: center;
        }

        img {
            width: 200px;
            height: 200px;
            border-radius: 50%;
            object-fit: cover;
        }

        table {
            margin: 0 auto;
            width: 80%;
            margin-top: 30px;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #fff;
        }

        th {
            background-color: #222;
            color: #fff;
            font-size: 18px;
        }

        td {
            background-color: #444;
            color: #fff;
            font-size: 16px;
        }

        .button-container {
            text-align: center;
            margin-top: 30px;
        }

        .button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .button:hover {
            background-color: #444;
        }

        footer {
            background-color: #222;
            padding: 20px;
            text-align: center;
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
        }

        footer p {
            margin: 0;
            color: #999;
            font-size: 14px;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}

<div class="profile-container">
    <img src="https://pic.rutubelist.ru/user/ce/e6/cee631c1e7c644dd11bb56730a0b2705.jpg" alt="Profile Image">
    <h4>{{ user.username }}</h4>
    <table>
        <tr>
            <th>Имя</th>
            <td>{{ user.first_name }}</td>
        </tr>
        <tr>
            <th>Фамилия</th>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Дата регистрации</th>
            <td>{{ user.date_joined }}</td>
        </tr>
    </table>
    <div class="button-container">
        <a href="{% url 'profile_edit' %}" class="button">Изменить данные</a>
    </div>
</div>

{% endblock %}

</body>
</html>

templates/login.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title>Login</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Login</h1>#}
{##}
{#    {% if messages %}#}
{#    <ul class="messages">#}
{#        {% for message in messages %}#}
{#        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#    {% endif %}#}
{##}
{#    <form method="post" action="{% url 'login' %}">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Login</button>#}
{#    </form>#}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        h1 {
            font-size: 32px;
            text-align: center;
            margin-top: 50px;
        }

        .messages {
            list-style: none;
            padding: 0;
            margin-top: 30px;
            text-align: center;
        }

        .messages li {
            font-size: 18px;
            margin-bottom: 10px;
        }

        .error {
            color: #ff0000;
        }

        .login-form {
            margin-top: 30px;
            text-align: center;
        }

        .login-form input[type="text"],
        .login-form input[type="password"] {
            width: 200px;
            padding: 5px;
            margin-bottom: 10px;
            font-size: 16px;
        }

        .login-form button[type="submit"] {
            padding: 10px 20px;
            font-size: 18px;
            background-color: #444;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .login-form button[type="submit"]:hover {
            background-color: #222;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    <h1>Авторизация</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="login-form">
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username"><br>
            <input type="password" name="password" placeholder="Password"><br>
            <button type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

</body>
</html>

templates/register.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title>Register</title>#}
{#</head>#}
{#<body>#}
{#{% extends 'home.html' %}#}
{#{% load static %}#}
{#{% block content %}#}
{#    <h1>Register</h1>#}
{##}
{#    {% if messages %}#}
{#        <ul class="messages">#}
{#            {% for message in messages %}#}
{#                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
{##}
{#    <form method="post" action="{% url 'register' %}">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Register</button>#}
{#    </form>#}
{#{% endblock %}#}
{##}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: "Arial", sans-serif;
        }

        h1 {
            font-size: 32px;
            text-align: center;
            margin-top: 50px;
        }

        form {
            margin-top: 50px;
            text-align: center;
        }

        form p {
            margin-bottom: 10px;
        }

        input[type="text"], input[type="password"] {
            padding: 10px;
            width: 300px;
            border: none;
            background-color: #333;
            color: #fff;
        }

        button {
            padding: 10px 20px;
            background-color: #222;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #444;
        }

        .messages {
            list-style: none;
            padding: 0;
            margin-top: 20px;
        }

        .messages li {
            margin-bottom: 10px;
            font-size: 16px;
        }

        .error {
            color: #ff0000;
        }

        .success {
            color: #00ff00;
        }

        .container {
            max-width: 450px;
            margin: 0 auto;
            padding: 70px;
            margin-top: 60px;
            background-color: #222;
            border-radius: 10px;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
{% extends 'home.html' %}
{% load static %}
{% block content %}
    {#    <h1>Register</h1>#}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="container">
        <h1>Регистрация</h1>

        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <p>
                <label for="id_username">Username:</label><br>
                {{ form.username }}
            </p>
            <p>
                <label for="id_firstname">Имя:</label><br>
                {{ form.first_name }}
            </p>
            <p>
                <label for="id_lastname">Фамилия:</label><br>
                {{ form.last_name }}
            </p> </p>
            <p>
                <label for="id_date_of_birth">День рождения:</label><br>
                {{ form.date_of_birth }}
            </p>
            <p>
                <label for="id_email">Email:</label><br>
                {{ form.email }}
            </p>
            <p>
                <label for="id_gender">Гендер:</label><br>
                {{ form.gender }}
            </p>
            <p>
                <label for="id_is_verified">Верификация :</label><br>
                {{ form.is_verified }}
            </p>
            <p>
                <label for="id_password1">Пароль:</label><br>
                {{ form.password1 }}
            </p>
            <p>
                <label for="id_password2">Подтверждение пароля:</label><br>
                {{ form.password2 }}
            </p>
            <button type="submit">Зарегистрироваться</button>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

</body>
</html>